# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'AMBNetworkRequestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AMBNetworkRequestDemo
  
  pod 'AMBNetworkRequest', :path => '../'
  pod 'YTKNetwork'
  pod 'YYModel'

  target 'AMBNetworkRequestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
